/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as UsoRouteImport } from './routes/uso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MaestroRouteImport } from './routes/maestro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoRoute = UsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroRoute = MaestroRouteImport.update({
  id: '/maestro',
  path: '/maestro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compras': typeof ComprasRoute
  '/contactos': typeof ContactosRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/maestro': typeof MaestroRoute
  '/perfil': typeof PerfilRoute
  '/uso': typeof UsoRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compras': typeof ComprasRoute
  '/contactos': typeof ContactosRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/maestro': typeof MaestroRoute
  '/perfil': typeof PerfilRoute
  '/uso': typeof UsoRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compras': typeof ComprasRoute
  '/contactos': typeof ContactosRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/maestro': typeof MaestroRoute
  '/perfil': typeof PerfilRoute
  '/uso': typeof UsoRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compras'
    | '/contactos'
    | '/gastos'
    | '/inventario'
    | '/login'
    | '/maestro'
    | '/perfil'
    | '/uso'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compras'
    | '/contactos'
    | '/gastos'
    | '/inventario'
    | '/login'
    | '/maestro'
    | '/perfil'
    | '/uso'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compras'
    | '/contactos'
    | '/gastos'
    | '/inventario'
    | '/login'
    | '/maestro'
    | '/perfil'
    | '/uso'
    | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComprasRoute: typeof ComprasRoute
  ContactosRoute: typeof ContactosRoute
  GastosRoute: typeof GastosRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  MaestroRoute: typeof MaestroRoute
  PerfilRoute: typeof PerfilRoute
  UsoRoute: typeof UsoRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso': {
      id: '/uso'
      path: '/uso'
      fullPath: '/uso'
      preLoaderRoute: typeof UsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro': {
      id: '/maestro'
      path: '/maestro'
      fullPath: '/maestro'
      preLoaderRoute: typeof MaestroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComprasRoute: ComprasRoute,
  ContactosRoute: ContactosRoute,
  GastosRoute: GastosRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  MaestroRoute: MaestroRoute,
  PerfilRoute: PerfilRoute,
  UsoRoute: UsoRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
